###
POST http://localhost:3000/cards HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "value": "4",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
POST http://localhost:3000/cards/getLastCard
Content-Type: application/json

{
    "game_id": "678ad5ec112c1d209ee0d510"
}


###
GET http://localhost:3000/cards HTTP/1.1

###
GET http://localhost:3000/cards/6790589b9d5e76e50c1a620c HTTP/1.1



###
PUT http://localhost:3000/cards/6790589b9d5e76e50c1a620c HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "value": "1",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
PATCH http://localhost:3000/cards/678ad57d112c1d209ee0d508 HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "value": "1",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
DELETE http://localhost:3000/cards/679058ba9d5e76e50c1a6211 HTTP/1.1


###
PUT http://localhost:3000/cards/play
Content-Type: application/json

{
  "userId": "67a90540ddb260dbebc75c3b",
  "gameId": "67c1117dea58ded9c4e5706f",
  "cardId": "67c130e4f51ca95baedf81bc" 
} 


###
PUT http://localhost:3000/cards/draw
Content-Type: application/json

{
  "userId": "67b610ebd76a2ee7647f1d21",
  "gameId": "67c1117dea58ded9c4e5706f"
}


###
PUT http://localhost:3000/cards/declare-uno
Content-Type: application/json

{
  "userId": "67a92543338e828ae2e77c5c",
  "gameId": "67b8999fe23dbeea70de2f46"
}

###
POST http://localhost:3000/cards/challenge-Uno
Content-Type: application/json

{
    "challengerId": "67b610ebd76a2ee7647f1d21",
    "challengedPlayerId": "67a90540ddb260dbebc75c3b",
    "gameId": "67b8999fe23dbeea70de2f46"
}


###
GET  http://localhost:3000/cards/player/67a92543338e828ae2e77c5c/hand

