###
POST http://localhost:3000/cards HTTP/1.1
Content-Type: application/json

{
    "color": "blue",
    "value": "4",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
GET http://localhost:3000/cards HTTP/1.1

###
GET http://localhost:3000/cards/6790589b9d5e76e50c1a620c HTTP/1.1

###
PUT http://localhost:3000/cards/6790589b9d5e76e50c1a620c HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "value": "1",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
PATCH http://localhost:3000/cards/678ad57d112c1d209ee0d508 HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "value": "1",
    "gameId": "678ad5ec112c1d209ee0d510"
}

###
DELETE http://localhost:3000/cards/6790525eff4243e1fe273680 HTTP/1.1