GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWFiYWNkY2YwODA5NzVjMDM5YzMwMyIsImVtYWlsIjoiZWR3aW5AZ21haWwuY29tIiwiaWF0IjoxNzM4MTkzNjYyLCJleHAiOjE3MzgxOTcyNjJ9.eaDaxz7WFAP1gXJeqLfF9D43vsYmVHU_mTRF09DRFgM
